### ISSUE TITLE
Only relays over one ERLite3

### ISSUE THREAD

**Issue by gorky** [britannic/ubnt-bcast-relay#3]
I am having a weird issue where broadcasts are only going over one ERLite3.  Setup is that Living room is general Entertainment (with it's own network and wiring), with Office having a couple of desks, including for my Spouse (who likes to Game).  I also have some additional networks (real & virtual) for work.  Steam Link sends UDP Discovery xx.xx.xx.255 port 27063.

Setup:
Steam Link -> ErLite3 (LR) -> ActionTec Router (House Backbone) -> ErLite3(Office) -> Office Computers (with Spouse Computer having games)

Software is installed on both ERLite3's.  Steam Link -> ErLite3(LR) is working.  Anything attached to the ActionTec sees the packets, although they have IP Address of the ErLite3, not the Steam Link (currently using Port Forwarding to handle the responses).  The Office ErLite3 is seeing the packets (I ran  tcpdump on the Office ErLite3 -- Steam packets were included in the dump), but is not rebroadcasting them.

I have been using wireshark to sniff out packets.  When using Wireshark, one can use the filter expression "udp contains 4c:5f:a0" to spot Steam Datagrams.

No errors or faults logged.
On the office ERLite3:
```
show service bcast-relay
 id 1 {
     description "Steam Listener"
     interface eth0
     interface eth2
     port 27036
 }
```
EdgeRouter Lite v1.10.7

**Comment by gorky** [comment]
Should probably have added -- this configuration is identical to the LR ERLite3.

**Comment by britannic** [comment]
Recommend you open a thread on the [Ubiquiti EdgeMax forum](https://community.ui.com/tags/edgemax) for configuration use cases like yours. This project was to simply provide an installation wrapper for [Joachim Breitner's brilliant udp-broadcast-relay software](www.joachim-breitner.de/udp-broadcast-relay/).

**Comment by gorky** [comment]
Any way to verify if there is an issue with installation or configuration?
