### ISSUE TITLE
Broadcasting on the original network no longer works

### ISSUE THREAD

**Issue by rcdailey** [britannic/ubnt-bcast-relay#4]
I have two subnets: `192.168.1.0/24` (also `eth1` on my USG) and `192.168.2.0/24` (also `eth1.2` on my USG). I have the following configuration:

```
"bcast-relay": {
  "id": {
    "1": {
      "description": "Logitech Harmony",
      "interface": [
        "eth1",
        "eth1.2"
      ],
      "port": "5224"
    }
  }
}
```

I am seeing responses from clients (Harmony Hub devices) on `192.168.2.x` now, but not for the 1 Harmony Hub I still have on `192.168.1.x`. Prior to enabling `bcast-relay`, I was getting the opposite: Responses from my `eth1` network but not `eth1.2`. My understanding is that both should be working. Is there something I'm doing wrong?

**Comment by britannic** [comment]
For support on configuration scenarios, please ask your question on the [Ubiquiti community forums](https://community.ui.com/questions/Multicast-Sonos-Phorus-and-Play-Fi-Broadcast-255-255-255-255-lessportgreater-Discovery-Solution/1ce890c2-5e7e-4ef2-a42a-e9c59444fd3f).
