### ISSUE TITLE
Not running on EdgeRouter X v2.0.9

### ISSUE THREAD

**Issue by GeoffWy** [britannic/ubnt-bcast-relay#5]
I was hoping this would be my solution to recognise DNLA servers across subnets but the relay does not seem to run. I installed on my EdgeRouter X v2.0.9 using install_ubnt_bcast_relay.v1.2 and that seemed to go OK. bcast-relay now appears in the config tree and I am able to configure it. The configuration is:
`    bcast-relay {
        id 1 {
            description "SSDP relay"
            interface switch0.3
            interface switch0.4
            interface switch0.5
            port 1900
        }
`
However, I am not detecting any relayed packets (using tcpdump and if I look for the process there is nothing running that looks like udp-bcast-relay or similar.

I don't have much expertise with the linux environment, so I may be doing something stupid, or it may be that something changed with ER-X V2 that is the problem. Any help gratefully received, Geoff

**Comment by britannic** [comment]
@GeoffWy, recommend you post your question in the [community.ui.com](https://community.ui.com/questions/Multicast-Sonos-Phorus-and-Play-Fi-Broadcast-255-255-255-255-lessportgreater-Discovery-Solution/1ce890c2-5e7e-4ef2-a42a-e9c59444fd3f#answer/c723faf7-439e-4a78-b346-7fa1d72b6d35) forum, where you'll benefit from joint experience of other Ubiquiti users.

**Comment by zenitraM** [comment]
The issue seems to be that the binary is not compiled properly for the ER-X architecture and probably requires a specific recompile:
```
admin@ubnt# /opt/vyatta/sbin/udp-bcast-relay
vbash: /opt/vyatta/sbin/udp-bcast-relay: cannot execute binary file
```

**Comment by zenitraM** [comment]
Turns out you just have to use the tarball from https://github.com/britannic/ubnt-bcast-relay/raw/master/ubnt-bcast-relay_ER-X.tgz instead. It would be nice if this was documented. Thanks for the awesome work btw.
