### ISSUE TITLE
Installation on UDM-Pro

### ISSUE THREAD

**Issue by narchibald** [britannic/ubnt-bcast-relay#6]
I have tried to install this on a dream machine pro. However, the directories that it's trying to install itself into do not exist. I created the missing /opt/vyatta directory structure which helped the script install itself part of the way. But it stops on the /config/scripts directory as this does not exist either. I can't work out where the ubnt-bcast-relay.pl file should be installed on the UbiOS? Are you able to advise on this?

Of course, even if I get the bits installed in the correct locations there is still the possibility the bcast-relay won't run. Baby steps I guess. Any help would be great. Thanks

**Comment by britannic** [comment]
The UDM Pro uses an entirely different OS and configuration system implemented using a Docker like container system. This integration only targets Vyatta/VyOS based routers, specifically EdgeOS. Recommend you post your questions to the [community.ui.com](https://community.ui.com) forum.
